// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Build from '../src/commands/build.js'
import Capture from '../src/commands/capture.js'
import Cat from '../src/commands/cat.js'
import Dir from '../src/commands/dir.js'
import Kv from '../src/commands/key-value.js'
import Sweep from '../src/commands/sweep.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['build', 'capture', 'cat', 'dir', 'kv', 'sweep'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'build': Build,
  'capture': Capture,
  'cat': Cat,
  'dir': Dir,
  'kv': Kv,
  'sweep': Sweep
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'build': {
      name: 'build',
      description: 'build a program for the v5 brain',
      alias: 'b',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'path to the program', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' }
      },
      path: './src/commands/build'
    },
  'capture': {
      name: 'capture',
      description: 'take a screen capture of the brain',
      alias: 'c',
      options: {
        'path': { type: 'z.string.optional', required: false, hasDefault: false, description: 'path to save the screen capture', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/capture'
    },
  'cat': {
      name: 'cat',
      description: 'read a file from flash',
      path: './src/commands/cat'
    },
  'dir': {
      name: 'dir',
      description: 'list files on flash',
      alias: 'ls',
      path: './src/commands/dir'
    },
  'kv': {
      name: 'kv',
      description: 'access a brain\'s system key/value configuration',
      path: './src/commands/key-value'
    },
  'sweep': {
      name: 'sweep',
      description: 'clean up program build outputs',
      alias: 's',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'path to save the screen capture', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' }
      },
      path: './src/commands/sweep'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
