// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Build from '../src/commands/build.js'
import Capture from '../src/commands/capture.js'
import Cat from '../src/commands/cat.js'
import Dir from '../src/commands/dir.js'
import Kv from '../src/commands/key-value.js'
import Sweep from '../src/commands/sweep.js'
import Upload from '../src/commands/upload.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['build', 'capture', 'cat', 'dir', 'kv', 'sweep', 'upload'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'build': Build,
  'capture': Capture,
  'cat': Cat,
  'dir': Dir,
  'kv': Kv,
  'sweep': Sweep,
  'upload': Upload
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'build': {
      name: 'build',
      description: 'build a program for the v5 brain',
      alias: 'b',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'path to the program', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' }
      },
      path: './src/commands/build'
    },
  'capture': {
      name: 'capture',
      description: 'take a screen capture of the brain',
      alias: 'c',
      options: {
        'path': { type: 'z.string.optional', required: false, hasDefault: false, description: 'path to save the screen capture', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/capture'
    },
  'cat': {
      name: 'cat',
      description: 'read a file from flash',
      path: './src/commands/cat'
    },
  'dir': {
      name: 'dir',
      description: 'list files on flash',
      alias: 'ls',
      path: './src/commands/dir'
    },
  'kv': {
      name: 'kv',
      description: 'access a brain\'s system key/value configuration',
      path: './src/commands/key-value'
    },
  'sweep': {
      name: 'sweep',
      description: 'clean up program build outputs',
      alias: 's',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'path to save the screen capture', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' }
      },
      path: './src/commands/sweep'
    },
  'upload': {
      name: 'upload',
      description: 'upload a program or file to a brain',
      alias: 'u',
      options: {
        'after': { type: 'z.enum.default', required: true, hasDefault: true, default: "none", description: 'action to perform on the brain after upload', short: 'af', enumValues: ["none","run","screen"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"none"}]}, validator: '(val) => true' },
        'slot': { type: 'z.coerce.number.min.max.default', required: true, hasDefault: true, default: 1, description: 'program slot', short: 's', min: 1, max: 8, minLength: 1, maxLength: 8, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1018,"end":1019,"loc":{"start":{"line":41,"column":57,"index":1018},"end":{"line":41,"column":58,"index":1019}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'name': { type: 'z.string.optional', required: false, hasDefault: false, description: 'the name of the program', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'description': { type: 'z.string.default', required: true, hasDefault: true, default: "v5x.dev", description: 'the description of the program', short: 'd', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"v5x.dev"}]}, validator: '(val) => true' },
        'icon': { type: 'z.enum.default', required: true, hasDefault: true, default: "cool-x", description: 'the program\'s file icon', short: 'i', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"cool-x"}]}, validator: '(val) => true' },
        'uncompressed': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'skip gzip compression before uploading', short: 'u', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1505,"end":1510,"loc":{"start":{"line":56,"column":45,"index":1505},"end":{"line":56,"column":50,"index":1510}},"value":false}}]}, validator: '(val) => true' },
        'file': { type: 'z.string.optional', required: false, hasDefault: false, description: 'a build artifact to upload', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'method to use when uploading binaries', enumValues: ["monolith","dual","diff"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/upload'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
