// hey this code seemed really goofy to me, so I changed it,
// see https://github.com/LemLib/v5-serial-protocol/blob/ef8df5019a5504b5b96fc887ef1587d9ecaa84ea/src/VexIniConfig.ts
// for unchanged code
// -@meisZWFLZ

import { type ZerobaseSlotNumber } from "./Vex.js";

class BaseIniBuilder {
  protected str = "";

  protected addLine(line: string): void {
    this.str += line + "\n";
  }

  addComment(comment: string): this {
    this.addLine(comment.length === 0 ? ";" : "; " + comment);
    return this;
  }

  getContent(): string {
    return this.str;
  }
}

class IniSectionBuilder<
  O extends Record<number | string, string | number>,
> extends BaseIniBuilder {
  constructor(
    public readonly name: string,
    private readonly object: O,
    private readonly keyTransform: (k: keyof O) => string = (k) => k.toString(),
  ) {
    super();
  }

  private addSingleObjProperty(
    key: keyof O,
    maxValueLength?: number,
    omitIfEmpty = false,
  ): void {
    const rawValue = this.object[key];
    if (rawValue == null) return;
    const value = rawValue.toString();
    if (omitIfEmpty && value.length === 0) return;

    const formattedKey = this.keyTransform(key).padEnd(12).slice(0, 12);
    const trimmedValue = value.slice(0, maxValueLength);
    this.addLine(`${formattedKey} = "${trimmedValue}"`);
  }

  addObjProperty(
    key: keyof O | Array<keyof O>,
    maxValueLength?: number,
    omitIfEmpty = false,
  ): this {
    for (const k of Array.isArray(key) ? key : [key]) {
      this.addSingleObjProperty(k, maxValueLength, omitIfEmpty);
    }
    return this;
  }

  addAllObjProps(maxValueLength?: number): this {
    for (const k of Object.keys(this.object)) {
      this.addSingleObjProperty(k, maxValueLength);
    }
    return this;
  }
}

class IniFileBuilder extends BaseIniBuilder {
  addSection(
    section: IniSectionBuilder<Record<number | string, string | number>>,
  ): this {
    this.addLine(`[${section.name}]`);
    this.str += section.getContent();
    return this;
  }

  addOptionalSection(
    section: IniSectionBuilder<Record<number | string, string | number>>,
  ): this {
    if (section.getContent().length === 0) return this;
    return this.addComment("").addSection(section);
  }
}

export class ProgramIniConfig {
  baseName = "slot_1";
  autorun = false;
  project = { version: "1", ide: "Unknown", file: "none" };
  program = {
    version: "1",
    name: "program",
    slot: 0 as ZerobaseSlotNumber,
    icon: "default.bmp",
    iconalt: "",
    description: "",
    date: "",
    timezone: "0",
  };

  config: Record<number, string> = { 22: "adi" };
  controller1: Record<string, string> = {};
  controller2: Record<string, string> = {};

  setProgramDate(date: Date): void {
    this.program.date = date.toISOString();
    const offset = Math.abs(date.getTimezoneOffset());
    const hours = (offset / 60) >>> 0;
    const minutes = offset - hours * 60;
    this.program.timezone =
      (date.getTimezoneOffset() > 0 ? "-" : "+") +
      this.dec2(hours) +
      ":" +
      this.dec2(minutes);
  }

  createIni(): string {
    if (this.program.date.length === 0) {
      this.setProgramDate(new Date());
    }
    return new IniFileBuilder()
      .addComment("")
      .addComment("VEX program ini file")
      .addComment("Generated by Vex V5 Serial Protocol Library")
      .addComment("")
      .addSection(
        new IniSectionBuilder("project", this.project)
          .addObjProperty("version")
          .addObjProperty("ide", 16)
          .addObjProperty("file"),
      )
      .addComment("")
      .addSection(
        new IniSectionBuilder("program", this.program)
          .addObjProperty("version")
          .addObjProperty("name", 32)
          .addObjProperty("slot")
          .addObjProperty("icon", 16)
          .addObjProperty("iconalt", 16, true)
          .addObjProperty("description", 256)
          .addObjProperty("date")
          .addObjProperty("timezone"),
      )
      .addComment("")
      .addSection(
        new IniSectionBuilder(
          "config",
          this.config,
          (k) => "port_" + this.dec2(k),
        ).addAllObjProps(),
      )
      .addOptionalSection(
        new IniSectionBuilder(
          "controller_1",
          this.controller1,
        ).addAllObjProps(),
      )
      .addOptionalSection(
        new IniSectionBuilder(
          "controller_2",
          this.controller2,
        ).addAllObjProps(),
      )
      .getContent();
  }

  dec2(value: number): string {
    return (value % 100).toString(10).padStart(2, "0").toUpperCase();
  }
}
